version: '3.8'

services:
  # PostgreSQL Database with embedded init script
  postgres:
    build:
      context: .
      dockerfile: postgres/Dockerfile
    environment:
      POSTGRES_DB: delivery_tracker
      POSTGRES_USER: delivery_user
      POSTGRES_PASSWORD: delivery_password
      POSTGRES_HOST_AUTH_METHOD: md5
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U delivery_user -d delivery_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://delivery_user:delivery_password@postgres:5432/delivery_tracker
      POSTGRES_USER: delivery_user
      POSTGRES_PASSWORD: delivery_password
      POSTGRES_DB: delivery_tracker
      NOMINATIM_BASE_URL: https://nominatim.openstreetmap.org
      CORS_ORIGINS: http://localhost:3000,http://127.0.0.1:3000
      LOG_LEVEL: INFO
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # SvelteKit Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8000/api/v1
    environment:
      VITE_API_URL: http://localhost:8000/api/v1
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s