version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: delivery_tracker_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: delivery_tracker
      POSTGRES_USER: ${POSTGRES_USER:-delivery_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-delivery_password}
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-delivery_user} -d delivery_tracker"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
    driver: local